#strategy parameters
AdversarialBIM: 
  n_subset_ul: 300
  pseudo_labeling: True
  diversity: False
  eps: 0.3
  eps_iter: 0.01
  nb_iter: 10
  norm: np.inf
  targeted: False
  rand_init: False
  rand_minmax: 0.3
  max_iter: 100

AdversarialPGD: 
  n_subset_ul: 300
  pseudo_labeling: True
  diversity: False
  eps: 0.25
  eps_iter: 0.01
  nb_iter: 10
  norm: np.inf
  targeted: False
  rand_init: True
  rand_minmax: 0.3
  max_iter: 100

AdversarialDeepFool: 
  max_iter: 10
  eps: 0.3
  n_subset_ul: 300
  pseudo_labeling: True
  diversity: False