#strategy parameters
AdvesarialBIM: 
  n_subset_ul: null
  pseudo_labeling: True
  diversity: False
  eps: 0.3
  eps_iter: 1e-2
  nb_iter: 1
  norm: np.inf
  targeted: False
  rand_init: False

AdvesarialPGD: 
  n_subset_ul: null
  pseudo_labeling: True
  diversity: False
  eps: 0.3
  eps_iter: 1e-2
  nb_iter: 1
  norm: np.inf
  targeted: False
  rand_init: True
  rand_minmax: 0.3

AdvesarialDeepFool: 
  max_iter: 10
  eps: 0.3
  n_subset_ul: null
  pseudo_labeling: True
  diversity: False