seeds:
  - 1380
  # - 1637
  # - 1549
strategies: 
  - AdversarialPGD
  - AdversarialBIM
  # - Random
  # - Margin
  # - AdversarialDeepFool
  # - LeastConfidence
  # - Entropy
  # - LeastConfidenceDropout
  # - MarginSamplingDropout
  # - EntropySamplingDropout
  - KMeansSampling
  # - CoreSet
  # - BALD
#
n_init_labeled: 100
n_query: 100
n_final_labeled: 10000
#get dataset
dataset_name: mnist
pool_size: 55000
n_adv_test: 300
#get net
reset: true
repeat: 0


advtrain_mode: false
reset: true
pseudo_labelling: false
max_iter: 100

#strategy parameters
AdversarialPGD: 
  n_subset_ul: 300
  pseudo_labeling: true
  diversity: false
  cumul: false
  norm: inf
  args:
    eps: 0.3
    eps_iter: 0.005
    nb_iter: 100
    norm: inf
    targeted: false
    rand_init: true
    rand_minmax: 0.1

#strategy parameters
AdversarialBIM: 
  n_subset_ul: 300
  pseudo_labeling: true
  diversity: false
  cumul: false
  norm: inf
  args:
    eps: 0.3
    eps_iter: 0.005
    nb_iter: 100
    norm: inf
    targeted: false
    rand_init: false

AdversarialDeepFool:
  n_subset_ul: 300
  pseudo_labeling: true
  diversity: false
  cumul: false
  norm: inf
# General train/test parameters
train_loader_args:
  batch_size: 128
  num_workers: 4

test_loader_args:
  batch_size: 128
  num_workers: 4

net_arch: lenet5
epochs: 20
# Optimizer parameters
optimizer:
  name: adam
  params:
    # weight_decay: 0.0005
    # momentum: 0.5 #0.9
    lr: 0.001 # initial_lr

# LR scheduling parameters
# scheduler: 
#   name: CyclicLR
#   params:
#     base_lr: 0.001
#     max_lr: 0.1
#     step_size_up: 20
#     mode: triangular2

scheduler: 
  name: None #CosineAnnealingLR
  params:
    T_max: 200

advtrain_attack:
  name: 'pgd'
  args:
    eps: 0.3
    eps_iter: 0.1
    nb_iter: 20
    norm: inf
    targeted: false
    rand_init: true

test_attack:
  name: 'pgd'
  args:
    eps: 0.3
    eps_iter: 0.1
    nb_iter: 20
    norm: inf
    targeted: false
    rand_init: true
    rand_minmax: 0.1

# test_attack:
#   name: 'deepfool'
#   args:
#     nb_iter: 20

dis_test_attack:
  name: 'deepfool'
  args:
    nb_iter: 100

# dis_test_attack:
#   name: 'pgd'
#   args:
#     eps: 0.3
#     eps_iter: 0.01
#     nb_iter: 50
#     norm: inf
#     targeted: false
#     rand_init: true
#     rand_minmax: 0.1