seeds:
  - 139937
  # - 973000
  # - 663829
strategies: 
  - RandomSampling
  - AdversarialPGD
  - MarginSampling
  # - AdversarialDeepFool
  # - LeastConfidence
  # - EntropySampling
  # - LeastConfidenceDropout
  # - MarginSamplingDropout
  # - EntropySamplingDropout
  # - KMeansSampling
  # - KCenterGreedy
  # - BALDDropout
  # - AdversarialBIM
#
n_init_labeled: 40000
n_query: 5000
n_final_labeled: 60000
#get dataset
dataset_name: mnist
pool_size: 60000
n_adv_test: 300
#get net
reset: true
repeat: 0

advtrain_mode: false
reset: true
pseudo_labelling: false
max_iter: 50
#strategy parameters

AdversarialPGD: 
  n_subset_ul: 300
  pseudo_labeling: false
  diversity: false
  cumul: False
  args:
    eps: 0.3
    eps_iter: 0.05
    nb_iter: 100
    norm: np.inf
    targeted: false
    rand_init: true


AdversarialDeepFool:
  n_subset_ul: 300
  pseudo_labeling: false
  diversity: false
  cumul: false

# General train/test parameters
train_loader_args:
  batch_size: 128
  num_workers: 4

test_loader_args:
  batch_size: 128
  num_workers: 4

net_arch: lenet5
epochs: 20
# Optimizer parameters
optimizer:
  name: adam
  params:
    # weight_decay: 0.0005
    # momentum: 0.5 #0.9
    lr: 0.001 # initial_lr

# LR scheduling parameters
# scheduler: 
#   name: CyclicLR
#   params:
#     base_lr: 0.001
#     max_lr: 0.1
#     step_size_up: 20
#     mode: triangular2

scheduler: 
  name: None #CosineAnnealingLR
  params:
    T_max: 200

advtrain_attack:
  name: 'pgd'
  args:
    eps: 0.3
    eps_iter: 0.1
    nb_iter: 20
    norm: np.inf
    targeted: false
    rand_init: true

test_attack:
  name: 'pgd'
  args:
    eps: 0.3
    eps_iter: 0.1
    nb_iter: 20
    norm: np.inf
    targeted: false
    rand_init: true

# test_attack:
#   name: 'deepfool'
#   args:
#     nb_iter: 20


dis_test_attack:
  name: 'pgd'
  args:
    eps: 0.3
    eps_iter: 0.1
    nb_iter: 20
    norm: np.inf
    targeted: false
    rand_init: true